version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: ticket_db
    environment:
      POSTGRES_DB: appTickets
      POSTGRES_USER: appUser
      POSTGRES_PASSWORD: appTicketsPassword2024
    ports:
      - "5432:5432"
     volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-slim
    container_name: app_java
    working_dir: /app
    volumes:
      - ./target:/app
    command: java -jar /app/mi-aplicacion.jar
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: